-- return {
--   -- TEST
--   s(
--     { -- Table 1: snippet parameters
--       trig="hi",
--       dscr="An autotriggering snippet that expands 'hi' into 'Hello, world!'",
--       regTrig=false,          -- tirgger is not lua regex (default)
--       priority=100,           -- default is 1000
--       snippetType="snippet",  -- autosnippet/snippet; snippet is default
--     },
--     { -- Table 2: snippet nodes
--       t("Hello, world!"),
--     }
--   ),
-- }
